### ISSUE TITLE
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'

### ISSUE THREAD

**Issue by Mordillo98** [trizen/oblogout-py3#11]
I'm having this error when executing oblogout in archlinux, april 2024.

Traceback (most recent call last): File "/bin/oblogout", line 103, in <module> sys.exit(main()) ^^^^^^ File "/bin/oblogout", line 98, in main app = OpenboxLogout(config, local_mode) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/site-packages/oblogout/__init__.py", line 90, in __init__ self.load_config(config) File "/usr/lib/python3.12/site-packages/oblogout/__init__.py", line 193, in load_config self.parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? 

What fixed it for me:

sudo nano /usr/lib/python3.12/site-packages/oblogout/__init__.py

found this line: self.parser = configparser.SafeConfigParser()

changed it to: self.parser = configparser.ConfigParser()

Thank you.

**Comment by trizen** [comment]
Fixed in https://github.com/trizen/oblogout-py3/pull/10. Install the latest commit.
