### ISSUE TITLE
ImportError: /usr/lib/libgirepository-1.0.so.1: undefined symbol: g_memdup2

### ISSUE THREAD

**Issue by chmol** [trizen/oblogout-py3#5]
I have the following issue, I tried installing from AUR then from here (stupidly expecting some change). I'm not sure how to debug it 

`└─> oblogout
Traceback (most recent call last):
  File "/usr/bin/oblogout", line 103, in <module>
    sys.exit(main())
  File "/usr/bin/oblogout", line 78, in main
    from oblogout import OpenboxLogout
  File "/usr/lib/python3.9/site-packages/oblogout/__init__.py", line 40, in <module>
    import gi
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgirepository-1.0.so.1: undefined symbol: g_memdup2
`

**Comment by trizen** [comment]
Strange. I also use ArchLinux, but I can't confirm this issue. Try to run in verbose mode to see if that helps: `oblogout -v`.

Also try to update/reinstall `gobject-introspection-runtime`.

**Comment by chmol** [comment]
Nevermind, I updated my system reinstalled and it work now. Sorry I should have done that first.
